{
    "Service": "/Demoapp/Services/SampleServiceV4.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/Demoapp/Actions/Service/DownloadStartedMessage.action",
    "OnFailure": "/Demoapp/Actions/Service/SyncFailureMessage.action"
}